language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"

install:
    - pip install cython nose .

before_script:
    - "export PYTHONPATH=$PYTHONPATH:`pwd`"
    - "uname -a"
    - "cd tests"

script: nosetests -vv

notifications:
    email:
        on_success: change
        on_failure: change
